demo/urls.py
from django.urls import path
from . import views
app_name='demo'
urlpatterns = [
    path('',views.index,name="index"),
    path('computer-specs',views.coputerSpecs,name="specs"),
    path('nots',views.nots,name="nots"),
    path('kill_process/<int:id>/',views.kill_process,name="kill_process"),
    path('kill/<int:id>/',views.kill,name="kill"),
    path('test/',views.test,name="chart"),
]

taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('demo.urls')),
    path('admin/', admin.site.urls),
]

demo/models.py
from django.db import models

# Create your models here.

demo/views.py
import json
from django.http import request
from django.http.response import JsonResponse
from django.shortcuts import render,redirect
import psutil
from django.contrib import messages

def nots(request):
    context = {
        'title': 'Computer Specs',
        'processes': getProcessInfo(),
        'ram': getRamInfo()
    }
    return JsonResponse(context)

def coputerSpecs(request):
    context = {
        'title': 'Computer Specs',
        'disk': diskInfo(),
        'cpu': cpuInfo(),
        'ram': getRamInfo()
    }
    return render(request,'computer-spec.html',context)

def test(request):
    context = {
        'title': 'Computer Specs',
        'processes': getProcessInfo(),
        'ram': getRamInfo()
    }
    return render(request,'chart.html',context)

    
def index(request):
    context = {
        'title': 'Process Management System v1',
        'disk': diskInfo(),
        'cpu': cpuInfo(),
        'ram': getRamInfo(),
        'processes': getProcessInfo()
    }
    return render(request,'base.html',context)

def kill(request,id):
    print(f'Deleting process with pid = {id}')
    try:
        # p = psutil.Process(id)
        # p.terminate() 
        print("---> OK Process killed  ")
        context = {
            'type': 'success',
            'msg': "OK Process killed",
            'data': getProcessInfo()
        }
        return JsonResponse(context)
    except:
        print("---> Failed to kill Process ! ")
        context = {
            'type': 'warning',
            'msg': "Failed to kill Process",
            'data': getProcessInfo()
        }
        return JsonResponse(context)    

def kill_process(request,id):
    print(f'Deleting process with pid = {id}')
    try:
        p = psutil.Process(id)
        p.terminate() 
        print("---> OK Process killed  ")
        messages.success(request,"OK Process killed")
    except:
        print("---> Failed to kill Process ! ")
        messages.warning(request,"Failed to kill Process")
    return redirect('demo:index')

def diskInfo():
    # Hard disk info
    disk = psutil.disk_usage('/')
    totalDisk = round(disk[0] / float(2**30),2)
    usedDisk = round(disk[1] / float(2**30),2)
    freeDisk = round(disk[2] / float(2**30),2)
    freeDiskPercent = round(disk[3],2)
    # add cpu info : intel core i9 etc...
    str1 = usedDisk,
    str2 = freeDisk
    diskInfo = {
        'listVal':[usedDisk,freeDisk],
        'listLab':["Used","Free"],
        'total':totalDisk,
        'freePercent':freeDiskPercent,
        'used': usedDisk,
        'free':freeDisk
    }
    return diskInfo

def cpuInfo():
    cpuCount = psutil.cpu_count()
    phyCpuCount = psutil.cpu_count(logical=False)
    cpuFreq = round(psutil.cpu_freq()[2] / float(1000),2)
    cpuUsage = round(psutil.cpu_percent(interval=None),2)
    cpuLeft = round(100 - cpuUsage,2) #int= None just for last call
    #print(f'Total: {cpuCount}, phyiscal: {phyCpuCount}, max freq: {cpuFreq} GHz,cpu usage: {cpuUsage} %, left: {cpuLeftPercent} %')
    cpuInfo = {
        'listVal':[cpuUsage,cpuLeft],
        'listLab':["Used","Free"],
        'total':cpuCount,
        'physical':phyCpuCount,
        'freq':cpuFreq,
        'used':cpuUsage,
        'free':cpuLeft
    }
    return cpuInfo

def getRamInfo():
    totalRam = psutil.virtual_memory().total / (1024 ** 3)
    usedRam = psutil.virtual_memory().percent
    freeRam  = round(100 - usedRam,2)
    data =  {
        "total":round(totalRam,2),
        "used":usedRam,
        "free":freeRam
    }
    return data

def getProcessInfo():
    L = []
    for proc in psutil.process_iter():
        try:
            data = {
                'pid':proc.pid,
                'name':proc.name(),
                'status':proc.status(),
                'mem': round(proc.memory_percent(),2),
                'cpu': round(proc.cpu_percent(),2)
            }
            L.append(data)
        except (psutil.NoSuchProcess, psutil.AccessDenied , psutil.ZombieProcess) :
            pass
    newlist = sorted(L, key=lambda d: d['mem'], reverse=True) 
    return newlist

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        .alert {
            margin-left: 38px;
              position: relative;
              padding: .75rem 1.25rem;
              margin-bottom: 1rem;
              border: 1px solid transparent;
              border-radius: .25rem;
              width: 481px;
              text-align: center;
          }
          .alert-success {
            color: #155724;
            background-color: #d4edda;
            border-color: #c3e6cb;
          }
          .alert-warning {
            color: #f1420c;
            background-color: #FFF7A8;
            border-color: #ffeeba;
          }
    </style>
</head>

<body>
    <div class="container-fluid">
        <div class="row mx-auto">
            <div class="col-6 border rounded my-3 mx-auto p-2 bg-light">
                <h2 class="text-center"> Task Management System </h2>
            </div>
        </div>
        <div class="container border border-warning rounded my-2">
            <h5 class="ml-4 mt-4 text-info"><span> <i class="fa fa-home" aria-hidden="true"></i> Home</span> / 
            <!--<span class="text-info"><a class="text-dark" href="/computer-specs"> Computer Specs </a> </span></h5>-->
                    
            <div class="row mx-auto my-2 p-2">
                <div class="col-8 border rounded mt-1 mx-auto p-4 bg-light">
                    <table class="table table-striped">
                        <thead>
                          <tr>
                            <th scope="col">PID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Status</th>
                            <th scope="col">Memory</th>
                            <th scope="col">CPU</th>
                            <th scope="col"></th>
                          </tr>
                        </thead>
                        <tbody>
                            {% for pr in processes %}
                          <tr>
                            <td class="text" scope="row">{{pr.pid}}</td>
                            <td class="text">{{pr.name}}</td>
                            <td class="text">{{pr.status}}</td>
                            <td class="text">{{pr.mem}} %</td>
                            <td class="text">{{pr.cpu}} %</td>
                            <td class=""><a  href="{% url 'demo:kill_process' pr.pid %}" id="{{pr.pid}}" class="btn"><span class="badge badge-primary p-2">KILL</span>
                            </a>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>


                    <!-- <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="text" scope="col">PID</th>
                                <th class="text" scope="col">Name</th>
                                <th class="text" scope="col">Status</th>
                                <th class="text" scope="col">Memory usage</th>
                                <th class="text" scope="col">CPU usage</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for pr in processes %}
                            <tr id="{{pr.pid}}tr">
                                <td class="text" scope="row">{{pr.pid}}</td>
                                <td class="text">{{pr.name}}</td>
                                <td class="text">{{pr.status}}</td>
                                <td class="text">{{pr.mem}} %</td>
                                <td class="text">{{pr.cpu}} %</td>
                                <td class=""><a  href="{% url 'demo:kill_process' pr.pid %}" id="{{pr.pid}}" class="btn"><span class="badge badge-primary p-2">KILL</span>
                                </a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                      </table> -->
                </div>
            </div>
        </div>
     
    </div>
   
</body>

</html>

templates/chart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>
<body>

    <div class="container-fluid border border-primary rounded">
        <div class="row mx-auto bg-dark p-4">
            <div class="col-6 mx-auto bg-light p-4">
                <div class="row mx-auto text-center">
                    <canvas id="cpuChart"  style="max-height: 480px; max-width:480px ;"></canvas>
                </div>
            </div>
        </div>
   </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    {% comment %} <script src="{% static 'main.js' %}"> </script> {% endcomment %}

    <script>
    var ctxD = document.getElementById("cpuChart").getContext('2d');
    var graphData = {
        type: 'doughnut',
        data: {
            labels: ["Used", "Free"],
            datasets: [{
                label: "Disk Usage",
                data: [0,0],
                backgroundColor: ["#007bff", "#6DE441"],
                hoverBackgroundColor: ["#FF5A5E", "#5AD3D1"]
            }]
        },
        options: {
            responsive: true,
            plugins: {
            legend: {
                position: 'top',
            },
            title: {
                display: true,
                text: 'RAM Usage (GB)'
            }
            }
        },
    }

    var myLineChart = new Chart(ctxD, graphData);

    console.log('Starting ...')
        setInterval(function() {
        $( document ).ready(function() {
            $.ajax({
                url: "{% url 'demo:nots' %}",
                //data :nb_nots,
                success: function(d) {
                    //$('#nots').html(data);
                    var newGDatat = graphData.data.datasets[0].data;
                    newGDatat.shift();
                    newGDatat.push(d.ram.used);
                    newGDatat.shift();
                    newGDatat.push(d.ram.free);
                    console.log("---> data = " + d);
                    console.log("---> new gData = " + newGDatat);
                    
                    graphData.data.datasets[0].data = newGDatat;
                    myLineChart.update();

                
                    {% comment %} $('#nots').html('<span class="badge">'+ data.nb_nots +'</span>'); {% endcomment %}
                }
            });
        });
        
        }, 5000);
  </script>
</body>
</html>

templates/computer-spec.html
<!--
    
    
    <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>
    <div class="container-fluid">
        <div class="row mx-auto">
            <div class="col-6 border rounded my-3 mx-auto p-2 bg-light">
                <h2 class="text-center"> Titre</h2>
            </div>
        </div>
        <div class="container border border-warning rounded mt-3" style="background-color: rgba(255, 255, 255, 0.794);">
            <div class="row mx-auto my-2 p-2">
                <h5 class="text-center"> <a class="text-dark" href="/"><span> <i class="fa fa-home" aria-hidden="true"></i> Home</span></a> / <span class="text-info">Computer Specs</span></h5>
            </div>
            <div class="row mx-auto p-2">
                <div class="col-6">
                    <h4 class="text-info bg-light border border-primary p-2 rounded text-center"> Hard Disk </h4>

                    <ul class="list-group">
                        <li class="list-group-item bg-light m-1  d-flex justify-content-between align-items-center">
                            Total Disk Space
                            <span class="py-2 badge badge-primary badge-pill">{{disk.total}} GB</span>
                        </li>
                        <li class="list-group-item bg-light m-1  d-flex justify-content-between align-items-center">
                            Used Space
                            <span class="py-2 badge badge-danger badge-pill">{{disk.used}} GB</span>
                        </li>
                        <li class="list-group-item bg-light m-1  d-flex justify-content-between align-items-center">
                            Free Space
                            <span class="py-2 badge badge-success badge-pill">{{disk.free}} GB</span>
                        </li>
                        <li class="list-group-item bg-light m-1  d-flex justify-content-between align-items-center">
                            Free Space
                            <span class="py-2 badge badge-success badge-pill">{{disk.freePercent}} %</span>
                        </li>
                    </ul>

                </div>
                <div cl class="col-6">
                    <h4 class="text-info bg-light border border-primary p-2 rounded text-center"> CPU </h4>


                    <ul class="list-group">
                        <li class="list-group-item bg-light m-1 d-flex justify-content-between align-items-center">
                            Used CPU
                            <span class="py-2 badge badge-danger badge-pill">{{cpu.used}} %</span>
                        </li>
                        <li class="list-group-item bg-light m-1 d-flex justify-content-between align-items-center">
                            Free CPU
                            <span class="py-2 badge badge-success badge-pill">{{cpu.free}} %</span>
                        </li>
                        <li class="list-group-item bg-light m-1 d-flex justify-content-between align-items-center">
                            Number of logical CPU cores
                            <span class="py-2 badge badge-primary badge-pill">{{cpu.total}}</span>
                        </li>
                        <li class="list-group-item bg-light m-1 d-flex justify-content-between align-items-center">
                            Number of physical CPU cores
                            <span class="py-2 badge badge-primary badge-pill">{{cpu.physical}}</span>
                        </li>
                        <li class="list-group-item bg-light m-1 d-flex justify-content-between align-items-center">
                            CPU Max Frequency
                            <span class="py-2 badge badge-primary badge-pill">{{cpu.freq}} GHz</span>
                        </li>
                    </ul>

                </div>
                <div class="col-6 my-3">
                    <h4 class="text-info bg-light border border-primary p-2 rounded text-center">RAM</h4>
                    <li class="list-group-item bg-light m-1 d-flex justify-content-between align-items-center">
                        Total RAM
                        <span class="py-2 badge badge-danger badge-pill">{{ram.total}} GB</span>
                    </li>
                    <li class="list-group-item bg-light m-1 d-flex justify-content-between align-items-center">
                        Used RAM
                        <span class="py-2 badge badge-success badge-pill">{{ram.used}} %</span>
                    </li>
                    <li class="list-group-item bg-light m-1 d-flex justify-content-between align-items-center">
                        Free RAM
                        <span class="py-2 badge badge-primary badge-pill">{{ram.free}} %</span>
                    </li>
                </div>
            </div>
        </div>
    </div>
 
</body>

</html>

-->

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Management</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>

    <div class="container-fluid">
        <div class="row mx-auto">
            <div class="col-6 border rounded my-3 mx-auto p-2 bg-light">
                <h2 class="text-center"> Task Management System </h2>
            </div>
        </div>
        <div class="container border border-warning rounded my-2">
            <div class="row mx-auto my-2 p-2">
                <h5 class="text-center text-info"><span> <i class="fa fa-home" aria-hidden="true"></i> Home</span> / 
                <span class="text-info"><a class="text-dark" href="/computer-specs"> Computer Specs </a> </span></h5>
                <div class="col-12 border rounded my-3 mx-auto p-4 bg-light">
                <table class="table table-striped">
                    <thead>
                        <tr>
                        <th class="text-center" scope="col">PID</th>
                        <th class="text-center" scope="col">Name</th>
                        <th class="text-center" scope="col">Status</th>
                        <th class="text-center" scope="col">Memory usage</th>
                        <th class="text-center" scope="col">CPU usage</th>
                        <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for pr in processes %}
                               <tr id="{{pr.pid}}tr">
                        <th class="text-center" scope="row">{{pr.pid}}</th>
                        <td class="text-center">{{pr.name}}</td>
                        <td class="text-center">{{pr.status}}</td>
                        <td class="text-center">{{pr.mem}} %</td>
                        <td class="text-center">{{pr.cpu}} %</td>
                        <td class=""><a  href="{% url 'demo:kill_process' pr.pid %}" id="{{pr.pid}}" class="btn"><span class="badge badge-primary p-2">KILL</span>
                        </a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                </div>
            </div>
        </div>
     
    </div>
   <!-- <script src="{% static 'task.js' %}" ></script> -->
   <script >
        {% comment %} function doJob(pid){
            console.log('btn clicked with id = '+ pid);
            document.getElementById(pid+"tr").style.display ="none";
        } {% endcomment %}
   </script>
   
</body>
</html>